#Type casting in Python refers to converting one data type to another. Python provides several functions for this, which are typically used to convert data between different types explicitly.
#Types of Type Casting
## ###
# 1. Explicit Type Cast##
#  This involves using Python's built-in functions to manually convert one data type into another. This method is under your control, and you decide when and where to perform the conversio###.

# Exam
# p#     int(): Converts to an int###e#     float(): Converts to a floating-point ####u3.S
#    str(): Converts to a####s4.rg.
#   list(): Converts t#### 5. ist.
#  tuple(): Converts t#### 6.a tuple.
# set(): Convertse###'
type(num_sm
# 2. I#### plicit T ype Casting
#This happens automatically when Python interprets and converts one data type to another during execution. This usually occurs when performing operations where one type can be safely e = int("hello")
except ValueError:
    print("Conversion failed!")

In [ ]:
#Type casting in Python refers to converting one data type to another. Python provides several functions for this, which are typically used to convert data between different types explicitly.
#Types of Type Casting

### 1. Explicit Type Casting
##### This involves using Python's built-in functions to manually convert one data type into another. This method is under your control, and you decide when and where to perform the conversion.

### Examples:
#### 1.int(): Converts to an integer.
#### 2.float(): Converts to a floating-point number.
#### 3. str(): Converts to a string.
#### 4. list(): Converts to a list.
#### 5.tuple(): Converts to a tuple.
#### 6.set(): Converts to a set.



This results in 6 unique combinations of different data types where implicit type casting occurs

In [1]:
name = "suresh"
age = 23
std_info = name + age 
print(std_info)

TypeError: can only concatenate str (not "int") to str

In [2]:
x = 3
y = 3.4
z = x+y
print(z)

6.4

#### Examples on Explisite type casting:

In [5]:
# 1.int to flaot
x = 45   # x is int
new_x = float(x) # using type casting convert int into float
print(new_x)
print(type(new_x)) 
# check data type of new_x

45.0
<class 'float'>

In [ ]:
#2.float to int
y = 2.4
n_y = int(y)
print(n_y)

In [ ]:
# 3.int to string
x = 4567
new_x = str(x)
print(new_x)
print(type(new_x))

In [ ]:
#4.float to string
y = 2.3
new_y = str(y)
print(new_y)
print(type(new_y))

In [6]:
# 5.sting to int
a="1009"
b=int(a)
print(b)
print(type(b))

1009
<class 'int'>

In [7]:
name = "Shubhangi"
name1 = int(name)
print(name1)

ValueError: invalid literal for int() with base 10: 'Shubhangi'

In [ ]:
# 6.sting to float
a="1009.67"
b=float(a)
print(b)

In [ ]:
name = "Rohini"
x = int(name)
print(x)
print(type(x))

In [ ]:
#7.list to set
list = [1,2,3,4,5,6]
new_set = set(list)
print(new_set)

In [ ]:
#WAP to remove duplicate values from list.
list1 = [1,2,1,2,3,4,5,6,6,7]
new_list = set(list1)
print(new_list)

In [ ]:
#8.list to tuple
list1=[1,2,4,4,5,6,6,2,8,9]
tup=tuple(list1)
print(tup)

In [ ]:
#9.list to string.
Name = ["Rohini","Afnan","Adesh","Sayli"]
New_Name = str(Name)
print(New_Name)
print(type(New_Name))

In [ ]:
# 10.tuple to set
tuple1=(1,2,3,4,5,6,4,8)
set2=set(tuple1)
print(set2)

In [ ]:
# 9.list to string
my_list = ['Python', 'is', 'awesome']
my_string = ' '.join(my_list)
print(my_string)

In [ ]:
#11.tuple to list 
tuple1 = (1,2,3,4,5)
tuple2 = list(tuple1)
print(tuple2)

In [ ]:
#12.tuple to string.
name = ("mango","banana","apple")
new_name = str(name)
print(new_name)

In [ ]:
# 13. set to list
set1 = {1,2,3,4,5}
list1 = list(set1)
print(list1)

In [ ]:
# 14.set to tuple
set1={1,2,3,4,5,6,7,8,9}
tup2=tuple(set1)
print(tup2)

In [ ]:
#15.set to string
fruits = {"banana","mango","apple"}
fruits2 = str(fruits)
print(fruits2)

In [ ]:
#16.dictionary to set
dict1 = {1:"name",2:"age"}
set1 = set(dict1)
print(set1)

In [ ]:
#17.dictionary to string
dict1 = {1:"name",2:"age"}
str1 = str(dict1)
print(str1)

In [ ]:
#18.dictionary to tuple.
dict1 = {1:"name",2:"age"}
str1 = tuple(dict1)
print(str1)

In [ ]:
#19.dictionary to list.
dict1 = {1:"name",2:"age"}
str1 = list(dict1)
print(str1)

### 2. Implicit Type Casting
#### This happens automatically when Python interprets and converts one data type to another during execution. This usually occurs when performing operations where one type can be safely promoted to another.

Data Types Interacting Through Implicit Casting:
int
float
complex
bool
Number of Combinations:
By pairing these types in operations, we get the following valid combinations:

int + float
int + complex
int + bool
float + int
float + bool
float + complex
bool + int
bool + float
bool + complex

In [ ]:
# int to float
x = 4
y = 3.4
z = x+y     # inter  z = 4.0+3.4  float + flaot
print(z)

In [ ]:
#int + complex
x = 4
y = 5+5j
z = x+y
print(z)

In [ ]:
#float + complex
x = 4.5
y = 5+5j
z = x+y
print(z)

In [ ]:
#bool + float
x = True
y = 4.5
z = x+y
print(z)

In [ ]:
#bool + int
x = True
y = 4
z = x+y
print(z)

In [ ]:
#bool + complex
x = False
y = 4+3j
z=x+y
print(z)

In [ ]:
name = "rikik"
age = 34